### ISSUE TITLE
Refactor Roadmap.

### ISSUE THREAD

**Issue by siddontang** [ledisdb/ledisdb#212]
A very huge change, maybe not backward compatibility.
- [ ]  New key encoding, different types with same key prefix can now be gathered together. Discuss with @leither.
- [ ]  Simplify code, origin seems a little chaos.
- [ ]  Simplify backend storage interface.
- [ ]  Try to support distributed storage, like HBase. 
- [ ]  Redis compatibility after key encoding finished. 

I have no enough time, hope I can keep on.
